# Jekyll 자동화 블로그 설정
# Claude MCP 서버와 연동된 완전 자동화 기술 블로그

# 사이트 기본 정보 (개인화 완료)
title: "재훈의 AI 자동화 블로그"
email: gkswogns2013@gmail.com
description: >- 
  컴퓨터과학부 2학년 재훈의 AI와 자동화 기술 블로그입니다. 
  Claude MCP 서버, Jekyll, GitHub Actions를 활용한 완전 자동화 시스템을 구축하고, 
  기술 창업을 목표로 다양한 개발 경험과 인사이트를 공유합니다.

# GitHub Pages 프로젝트 사이트 설정 (404 오류 해결)
baseurl: "/my-jekyll-blog" # GitHub Pages 프로젝트 사이트용
url: "https://elecsonj.github.io" # GitHub Pages 도메인

# 소셜 미디어 및 개인 정보 (개인화 완료)
github_username: elecsonJ
twitter_username: # 트위터 사용시 추가
linkedin_username: # 링크드인 사용시 추가

# 개인 소개
author:
  name: "한재훈"
  bio: "컴퓨터과학부 2학년, AI 자동화 시스템 개발자, 기술 창업 준비중"
  location: "Seoul, Korea"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/elecsonJ"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"  
      url: "mailto:gkswogns2013@gmail.com"

# 테마 및 플러그인 설정 (UI 개선)
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# SEO 최적화
lang: ko
timezone: Asia/Seoul

# 페이지네이션 설정
paginate: 5
paginate_path: "/page:num/"

# 콘텐츠 설정
show_excerpts: true
excerpt_separator: <!--more-->

# 소셜 미디어 카드
social:
  name: 한재훈
  links:
    - https://github.com/elecsonJ
    - https://elecsonj.github.io/my-jekyll-blog

# Google Analytics (나중에 추가)
# google_analytics: G-XXXXXXXXXX

# Disqus 댓글 (나중에 추가)  
# disqus:
#   shortname: my-jekyll-blog

# 카테고리 및 태그 설정
collections:
  categories:
    output: true
    permalink: /:collection/:name/
  tags:
    output: true
    permalink: /:collection/:name/

# 기본 설정
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 퍼머링크 설정 (포스트 URL 구조)
permalink: /:categories/:year/:month/:day/:title/

# 빌드 설정
safe: true
incremental: false
profile: false

# Jekyll 성능 최적화
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# 파일 제외 설정
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts/
  - README.md
  - LICENSE
  - .github/

# 사이트 네비게이션
header_pages:
  - about.md
  - categories.md
  - tags.md

# 자동화 관련 커스텀 변수
automation:
  claude_mcp: true
  github_actions: true
  auto_posting: true
  seo_optimization: true
  
# 블로그 메타 정보
blog:
  founded: 2025
  focus: ["AI", "자동화", "Jekyll", "GitHub Actions", "창업"]
  tech_stack: ["Python", "Jekyll", "Claude MCP", "GitHub Actions", "Ruby"]
