# Jekyll 자동화 블로그 설정
# Claude MCP 서버와 연동하여 완전 자동화된 기술 블로그

# 사이트 기본 정보 (개인화 완료)
title: "재훈의 AI 자동화 블로그"
email: gkswogns2013@gmail.com
description: >- 
  서울시립대학교 컴퓨터과학부 2학년 재훈의 AI와 자동화 기술 블로그입니다. 
  Claude MCP 서버, Jekyll, GitHub Actions를 활용한 완전 자동화 기술 시스템을 구축하였고, 
  기술 창업을 목표로 다양한 개발과 연구를 진행하는 공간을 제공합니다.

# GitHub Pages 프로젝트 사이트 설정
baseurl: "/my-jekyll-blog"
url: "https://elecsonj.github.io"

# 개인 정보 (간소화하여 정확)
github_username: elecsonJ
twitter_username: 
linkedin_username: 

# 작성자 정보 (단순 문자열로 변경)
author: "한재훈 (Jaehoon Han)"
author_bio: "서울시립대학교 컴퓨터과학부 2학년 | University of Seoul, Computer Science & Engineering"
author_location: "서울, 대한민국 | Seoul, South Korea"
author_email: "gkswogns2013@gmail.com"
author_github: "elecsonJ"

# 대학교 정보
university:
  korean: "서울시립대학교 컴퓨터과학부"
  english: "University of Seoul, Department of Computer Science & Engineering"
  location: "Seoul, South Korea"
  website: "https://uos.ac.kr"

# 테마 및 플러그인 설정
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# SEO 최적화
lang: ko-KR
timezone: Asia/Seoul

# 페이지네이션 설정
paginate: 5
paginate_path: "/page:num/"

# 콘텐츠 설정
show_excerpts: true
excerpt_separator: <!--more-->

# 소셜 미디어 링크 (간단 정보)
social:
  name: "한재훈"
  links:
    - "https://github.com/elecsonJ"
    - "https://elecsonj.github.io/my-jekyll-blog"

# 구글 웹마스터 도구 (후에 추가 예정)
google_site_verification: # Google Search Console 등록 후 추가
google_analytics: # Google Analytics 설정 후 추가

# 사이트 키워드 정보
site_keywords: "AI, 자동화, Jekyll, GitHub Actions, 서울시립대, 컴퓨터과학, 기술창업, Claude MCP"

# 기본 설정
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: true

# 퍼마링크 설정
permalink: /:categories/:year/:month/:day/:title/

# 빌드 설정
safe: true
incremental: false
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# 파일 제외 설정
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - scripts/
  - README.md
  - LICENSE
  - .github/

# 헤더 네비게이션
header_pages:
  - about.markdown
  - categories.markdown

# 자동화 관련 설정
automation:
  claude_mcp: true
  github_actions: true
  auto_posting: true
  seo_optimization: true
  
# 블로그 메타 정보
blog:
  founded: 2025
  focus: ["AI", "자동화", "Jekyll", "GitHub Actions", "창업"]
  tech_stack: ["Python", "Jekyll", "Claude MCP", "GitHub Actions", "Ruby"]
  target_audience: "개발자, AI 연구자, 기술 창업자"

# 카테고리 시스템 설정
categories:
  # 한국어 카테고리
  korean:
    tech: "기술"
    ai: "인공지능"
    automation: "자동화"
    study: "학습"
    project: "프로젝트"
    startup: "창업"
  # 영어 카테고리  
  english:
    tech: "Technology"
    ai: "Artificial Intelligence" 
    automation: "Automation"
    study: "Study"
    project: "Project"
    startup: "Startup"

# 다국어 지원
languages:
  korean:
    name: "한국어"
    posts_title: "최신 포스트"
    about_title: "소개"
    contact_title: "연락처"
  english:
    name: "English"
    posts_title: "Latest Posts"
    about_title: "About"
    contact_title: "Contact"

# 기본 언어
default_language: korean