# Jekyll 자동화 블로그 구성 설정
# Claude MCP 서버와 연동하여 AI 자동화 블로그 구성 텍스트

# 사이트 기본 정보 (가장 기본적인 설정에만 필요함)
title: "재훈의 AI 자동화 블로그"
email: gkswogns2013@gmail.com
description: >- 
  서울시립대학교 컴퓨터과학부 2학년 한재훈의 AI와 자동화 기술 개인 개발과 
  Claude MCP 서버, Jekyll, GitHub Actions를 활용한 AI 자동화 블로그 시스템을 구성하고, 
  기술 데이터를 모두 진행하며 웹 개발에서 자동 가능한 플랫폼을 제공하는 개인의 지속적인 탐구를 제공합니다.

# GitHub Pages 플랫폼 사이트 설정
baseurl: "/my-jekyll-blog"
url: "https://elecsonj.github.io"

# 개인 정보 (가장 기본적인 설정)
github_username: elecsonJ
twitter_username: 
linkedin_username: 

# 작성자 정보 (더그램터 오뎅 자도가 윈가릴 필요함)
author: "한재훈 (Jaehoon Han)"
author_bio: "서울시립대학교 컴퓨터과학부 2학년 | University of Seoul, Computer Science & Engineering"
author_location: "서울, 대한민국 | Seoul, South Korea"
author_email: "gkswogns2013@gmail.com"
author_github: "elecsonJ"

# 대학교 정보
university:
  korean: "서울시립대학교 컴퓨터과학부"
  english: "University of Seoul, Department of Computer Science & Engineering"
  location: "Seoul, South Korea"
  website: "https://uos.ac.kr"

# 테마 및 플러그인 설정 - MINIMA 테마 제거하여 자동 Posts 생성 방지
# theme: minima  # 이 줄을 주석처리하여 자동 Posts 생성 방지
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# SEO 최적화 설정
lang: ko-KR
timezone: Asia/Seoul

# SEO 헤더 정보
seo:
  title: "재훈의 AI 자동화 블로그 | Jekyll & GitHub Actions"
  description: "AI, 자동화, Jekyll, GitHub Actions를 활용한 기술 블로그. 서울시립대학교 한재훈의 기술 데이터 분석 여정"
  image: "/assets/images/blog-cover.jpg"  # 차후 추가
  author: "한재훈 (Jaehoon Han)"

# 구글 사이트 도메인 설정 (차후 추가)
google_site_verification: "google52bf202f8d3f7884"
google_analytics:  # Google Analytics 차후 ID (GA4 형식: G-XXXXXXXXXX)

# 사이트 키워드 정보 (SEO용)
site_keywords: "AI, 자동화, Jekyll, GitHub Actions, 서울시립대학교, 컴퓨터과학, 기술데이터, Claude MCP, Python, 블로그, 블로그자동화"

# 페이지 설정
paginate: 10
paginate_path: "/page:num/"

# 콘텐츠 설정
show_excerpts: true
excerpt_separator: <!--more-->

# 소셜 네트워크 설정 (아직 정보)
social:
  name: "한재훈"
  links:
    - "https://github.com/elecsonJ"
    - "https://elecsonj.github.io/my-jekyll-blog"

# 기본 설정
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: true

# 퍼말링크 설정 (SEO 최적화)
permalink: /:categories/:year/:month/:day/:title/

# 빌드 설정
safe: true
incremental: false
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# 파일 제외 설정
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - scripts/
  - README.md
  - LICENSE
  - .github/

# 헤더 네비게이션
header_pages:
  - about.markdown
  - categories.markdown

# 자동화 관련 설정
automation:
  claude_mcp: true
  github_actions: true
  auto_posting: true
  seo_optimization: true
  
# 블로그 헤더 정보
blog:
  founded: 2025
  focus: ["AI", "자동화", "Jekyll", "GitHub Actions", "데이터"]
  tech_stack: ["Python", "Jekyll", "Claude MCP", "GitHub Actions", "Ruby"]
  target_audience: "개발자, AI 연구자, 기술 데이터자"

# 카테고리 시스템 설정 (실제 사용 중인 5개 체계)
categories:
  korean:
    news: "뉴스"
    analysis: "심층 분석" 
    dev: "개발"
    projects: "프로젝트"
    essay: "에세이"
  english:
    news: "News"
    analysis: "Analysis"
    dev: "Dev" 
    projects: "Projects"
    essay: "Essay"

# 다국어 지원
languages:
  korean:
    name: "한국어"
    posts_title: "최근 포스트"
    about_title: "소개"
    contact_title: "연락처"
  english:
    name: "English"
    posts_title: "Latest Posts"
    about_title: "About"
    contact_title: "Contact"

# 기본 언어
default_language: korean

# Jekyll SEO Tag 플러그인 설정
title_separator: "|"
tagline: "AI 자동화 기술 블로그"

# JSON-LD 구조화 데이터
structured_data:
  type: "Blog"
  author:
    type: "Person"
    name: "한재훈"
    url: "https://elecsonj.github.io/my-jekyll-blog"
  publisher:
    type: "Person"
    name: "한재훈"
    logo:
      type: "ImageObject"
      url: "https://elecsonj.github.io/my-jekyll-blog/assets/images/logo.png"